steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Abrufen der .tfvars-Datei aus dem Secret Manager
        gcloud secrets versions access latest --secret=tfvarsTEST > /workspace/a.txt
        head a.txt